# BWF Dataset 2018 to 2021

## On the BWF World Tour, does the number of matches or games played prior to the current tournament impact the player's tournament outcome?

In [484]:
# load libraries
import pandas as pd
import numpy as np

# Settings
pd.set_option('display.max_columns', None)

In [485]:
# load csv file
df = pd.read_csv(r'data\ms.csv')

In [486]:
print(f"Sample 5 rows:\n{df.head(5)}")
print(f"data frame dtypes:\n{df.dtypes}")
print(f"Field NA count:\n{df.isna().sum()}")

Sample 5 rows:
                                     tournament     city   country  \
0  PRINCESS SIRIVANNAVARI Thailand Masters 2018  Bangkok  Thailand
1  PRINCESS SIRIVANNAVARI Thailand Masters 2018  Bangkok  Thailand
2  PRINCESS SIRIVANNAVARI Thailand Masters 2018  Bangkok  Thailand
3  PRINCESS SIRIVANNAVARI Thailand Masters 2018  Bangkok  Thailand
4  PRINCESS SIRIVANNAVARI Thailand Masters 2018  Bangkok  Thailand

         date                tournament_type discipline  \
0  09-01-2018  HSBC BWF World Tour Super 300         MS
1  09-01-2018  HSBC BWF World Tour Super 300         MS
2  09-01-2018  HSBC BWF World Tour Super 300         MS
3  09-01-2018  HSBC BWF World Tour Super 300         MS
4  09-01-2018  HSBC BWF World Tour Super 300         MS

                       round  winner  nb_sets  retired game_1_score  \
0  Qualification round of 16       1        3    False        11-21
1  Qualification round of 16       1        2    False         21-7
2  Qualification round of 16       1        3    False        21-16
3  Qualification round of 16       1        2    False        21-17
4  Qualification round of 16       2        2    False        13-21

  game_2_score game_3_score  team_one_players         team_two_players  \
0        21-18         21-9     Jun Hao Leong  Kantawat Leelavechabutr
1        21-18          NaN      Teck Zhi Soo   Chico Aura Dwi Wardoyo
2         8-21        23-21     Mek Narongrit            Yee Han Chong
3         21-7          NaN  Mithun Manjunath      Henrikho Kho Wibowo
4        13-21          NaN        Chirag Sen          Hashiru Shimono

  team_one_nationalities team_two_nationalities  team_one_total_points  \
0                    MAS                    THA                     53
1                    MAS                    INA                     42
2                    THA                    MAS                     52
3                    IND                    INA                     42
4                    IND                    JPN                     26

   team_two_total_points  team_one_most_consecutive_points  \
0                     48                                 8
1                     25                                 9
2                     58                                 4
3                     24                                14
4                     42                                 4

   team_two_most_consecutive_points  team_one_game_points  \
0                                 9                     5
1                                 5                     3
2                                 7                     6
3                                 4                     2
4                                 5                     0

   team_two_game_points  team_one_most_consecutive_points_game_1  \
0                     1                                        3
1                     0                                        5
2                     1                                        4
3                     0                                        5
4                     3                                        4

   team_two_most_consecutive_points_game_1  team_one_game_points_game_1  \
0                                        9                            0
1                                        1                            1
2                                        4                            2
3                                        4                            1
4                                        5                            0

   team_two_game_points_game_1  \
0                            1
1                            0
2                            0
3                            0
4                            1

                                       game_1_scores  \
0  ['0-0', '1-0', '2-0', '3-0', '3-1', '4-1', '4-...
1  ['0-0', '1-0', '2-0', '3-0', '4-0', '4-1', '5-...
2  ['0-0', '1-0', '2-0', '2-1', '3-1', '4-1', '5-...
3  ['0-0', '0-1', '1-1', '1-2', '2-2', '3-2', '3-...
4  ['0-0', '1-0', '2-0', '2-1', '2-2', '2-3', '3-...

   team_one_most_consecutive_points_game_2  \
0                                      4.0
1                                      6.0
2                                      2.0
3                                     12.0
4                                      3.0

   team_two_most_consecutive_points_game_2  team_one_game_points_game_2  \
0                                      4.0                          2.0
1                                      5.0                          2.0
2                                      6.0                          0.0
3                                      3.0                          1.0
4                                      4.0                          0.0

   team_two_game_points_game_2  \
0                          0.0
1                          0.0
2                          1.0
3                          0.0
4                          2.0

                                       game_2_scores  \
0  ['0-0', '0-1', '1-1', '1-2', '2-2', '2-3', '3-...
1  ['0-0', '1-0', '2-0', '3-0', '4-0', '5-0', '6-...
2  ['0-0', '0-1', '0-2', '0-3', '1-3', '2-3', '2-...
3  ['0-0', '1-0', '2-0', '3-0', '4-0', '5-0', '6-...
4  ['0-0', '1-0', '2-0', '3-0', '3-1', '4-1', '4-...

   team_one_most_consecutive_points_game_3  \
0                                      8.0
1                                      NaN
2                                      4.0
3                                      NaN
4                                      NaN

   team_two_most_consecutive_points_game_3  team_one_game_points_game_3  \
0                                      2.0                          3.0
1                                      NaN                          NaN
2                                      7.0                          4.0
3                                      NaN                          NaN
4                                      NaN                          NaN

   team_two_game_points_game_3  \
0                          0.0
1                          NaN
2                          0.0
3                          NaN
4                          NaN

                                       game_3_scores
0  ['0-0', '1-0', '1-1', '2-1', '3-1', '4-1', '4-...
1                                                 []
2  ['0-0', '1-0', '2-0', '3-0', '4-0', '4-1', '4-...
3                                                 []
4                                                 []
data frame dtypes:
tournament                                     str
city                                           str
country                                        str
date                                           str
tournament_type                                str
discipline                                     str
round                                          str
winner                                       int64
nb_sets                                      int64
retired                                       bool
game_1_score                                   str
game_2_score                                   str
game_3_score                                   str
team_one_players                               str
team_two_players                               str
team_one_nationalities                         str
team_two_nationalities                         str
team_one_total_points                        int64
team_two_total_points                        int64
team_one_most_consecutive_points             int64
team_two_most_consecutive_points             int64
team_one_game_points                         int64
team_two_game_points                         int64
team_one_most_consecutive_points_game_1      int64
team_two_most_consecutive_points_game_1      int64
team_one_game_points_game_1                  int64
team_two_game_points_game_1                  int64
game_1_scores                                  str
team_one_most_consecutive_points_game_2    float64
team_two_most_consecutive_points_game_2    float64
team_one_game_points_game_2                float64
team_two_game_points_game_2                float64
game_2_scores                                  str
team_one_most_consecutive_points_game_3    float64
team_two_most_consecutive_points_game_3    float64
team_one_game_points_game_3                float64
team_two_game_points_game_3                float64
game_3_scores                                  str
dtype: object
Field NA count:
tournament                                    0
city                                          0
country                                       0
date                                          0
tournament_type                               0
discipline                                    0
round                                         0
winner                                        0
nb_sets                                       0
retired                                       0
game_1_score                                  0
game_2_score                                 37
game_3_score                               2448
team_one_players                              0
team_two_players                              0
team_one_nationalities                        0
team_two_nationalities                        0
team_one_total_points                         0
team_two_total_points                         0
team_one_most_consecutive_points              0
team_two_most_consecutive_points              0
team_one_game_points                          0
team_two_game_points                          0
team_one_most_consecutive_points_game_1       0
team_two_most_consecutive_points_game_1       0
team_one_game_points_game_1                   0
team_two_game_points_game_1                   0
game_1_scores                                 0
team_one_most_consecutive_points_game_2      38
team_two_most_consecutive_points_game_2      38
team_one_game_points_game_2                  38
team_two_game_points_game_2                  38
game_2_scores                                29
team_one_most_consecutive_points_game_3    2459
team_two_most_consecutive_points_game_3    2459
team_one_game_points_game_3                2459
team_two_game_points_game_3                2459
game_3_scores                                38
dtype: int64

In [487]:
# Create Tournament round ranking mapping
round_list = df['round'].unique().tolist()
round_list = pd.DataFrame({'round': round_list})
print(f"list of the rounds:{round_list}")

# DELETE Later - drop list to csv to create mapping
#round_list.to_csv(r'data/round_list_for_mapping.csv')

# return every unique tournament round pattern:
unique_rounds = df.groupby('tournament')['round'].unique()
unique_rounds_set = unique_rounds.apply(set)
unique_structures = list(unique_rounds_set)
has_duplicates = len(unique_structures) != len(set(map(frozenset, unique_structures)))
print(f"Is there duplicates in the set?{has_duplicates}")

for structure in set(map(frozenset, unique_structures)):
    print(structure)

# Manually rank rounds for each unique structure
# Define rankings for each unique structure
manual_rankings = {
    frozenset({'Round of 32', 'Qualification round of 16', 'Round of 64', 'Semi final', 'Final', 'Quarter final', 'Round of 16'}): {
        'Final': 1, 'Semi final': 2, 'Quarter final': 3, 'Round of 16': 4, 'Round of 32': 5, 'Round of 64': 6, 'Qualification round of 16': 7
    },
    frozenset({'Round 1', 'Semi final', 'Final', 'Round 3', 'Round 2'}): {
        'Final': 1, 'Semi final': 2, 'Round 3': 3, 'Round 2': 4, 'Round 1': 5
    },
    frozenset({'Round of 32', 'Semi final', 'Round of 64', 'Final', 'Quarter final', 'Round of 16'}): {
        'Final': 1, 'Semi final': 2, 'Quarter final': 3, 'Round of 16': 4, 'Round of 32': 5, 'Round of 64': 6
    },
    frozenset({'Qualification quarter final', 'Round of 32', 'Qualification round of 16', 'Semi final', 'Final', 'Quarter final', 'Round of 16'}): {
        'Final': 1, 'Semi final': 2, 'Quarter final': 3, 'Round of 16': 4, 'Round of 32': 5, 'Qualification quarter final': 6, 'Qualification round of 16': 7
    },
    frozenset({'Round of 32', 'Semi final', 'Final', 'Quarter final', 'Round of 16'}): {
        'Final': 1, 'Semi final': 2, 'Quarter final': 3, 'Round of 16': 4, 'Round of 32': 5
    },
    frozenset({'Qualification round of 16', 'Qualification round of 32', 'Final', 'Round of 32', 'Round of 64', 'Semi final', 'Quarter final', 'Round of 16'}): {
        'Final': 1, 'Semi final': 2, 'Quarter final': 3, 'Round of 16': 4, 'Round of 32': 5, 'Round of 64': 6, 'Qualification round of 16': 7, 'Qualification round of 32': 8
    }
}


# Map rankings back to the tournaments
# Create a mapping of tournaments to their unique round structure rankings
def get_round_rank(row):
    # Find the unique structure for the tournament
    structure = frozenset(unique_rounds[row['tournament']])
    # Get the ranking for the specific round
    return manual_rankings[structure][row['round']]

df['round_rank'] = df.apply(get_round_rank, axis=1)

# Display the results
print("DataFrame with Round Rankings:")
df

list of the rounds:                          round
0     Qualification round of 16
1   Qualification quarter final
2                   Round of 32
3                   Round of 16
4                 Quarter final
5                    Semi final
6                         Final
7     Qualification round of 32
8                   Round of 64
9                       Round 1
10                      Round 2
11                      Round 3
Is there duplicates in the set?True
frozenset({'Round of 32', 'Qualification round of 16', 'Round of 64', 'Semi final', 'Final', 'Quarter final', 'Round of 16'})
frozenset({'Round 1', 'Semi final', 'Final', 'Round 3', 'Round 2'})
frozenset({'Round of 32', 'Semi final', 'Round of 64', 'Final', 'Quarter final', 'Round of 16'})
frozenset({'Qualification quarter final', 'Round of 32', 'Qualification round of 16', 'Semi final', 'Final', 'Quarter final', 'Round of 16'})
frozenset({'Round of 32', 'Semi final', 'Final', 'Quarter final', 'Round of 16'})
frozenset({'Qualification round of 16', 'Qualification round of 32', 'Final', 'Round of 32', 'Round of 64', 'Semi final', 'Quarter final', 'Round of 16'})
DataFrame with Round Rankings:

,tournament,city,country,date,tournament_type,discipline,round,winner,nb_sets,retired,game_1_score,game_2_score,game_3_score,team_one_players,team_two_players,team_one_nationalities,team_two_nationalities,team_one_total_points,team_two_total_points,team_one_most_consecutive_points,team_two_most_consecutive_points,team_one_game_points,team_two_game_points,team_one_most_consecutive_points_game_1,team_two_most_consecutive_points_game_1,team_one_game_points_game_1,team_two_game_points_game_1,game_1_scores,team_one_most_consecutive_points_game_2,team_two_most_consecutive_points_game_2,team_one_game_points_game_2,team_two_game_points_game_2,game_2_scores,team_one_most_consecutive_points_game_3,team_two_most_consecutive_points_game_3,team_one_game_points_game_3,team_two_game_points_game_3,game_3_scores,round_rank
0,PRINCESS SIRIVANNAVARI Thailand Masters 2018,Bangkok,Thailand,09-01-2018,HSBC BWF World Tour Super 300,MS,Qualification round of 16,1,3,False,11-21,21-18,21-9,Jun Hao Leong,Kantawat Leelavechabutr,MAS,THA,53,48,8,9,5,1,3,9,0,1,"['0-0', '1-0', '2-0', '3-0', '3-1', '4-1', '4-...",4.0,4.0,2.0,0.0,"['0-0', '0-1', '1-1', '1-2', '2-2', '2-3', '3-...",8.0,2.0,3.0,0.0,"['0-0', '1-0', '1-1', '2-1', '3-1', '4-1', '4-...",7
1,PRINCESS SIRIVANNAVARI Thailand Masters 2018,Bangkok,Thailand,09-01-2018,HSBC BWF World Tour Super 300,MS,Qualification round of 16,1,2,False,21-7,21-18,NaN,Teck Zhi Soo,Chico Aura Dwi Wardoyo,MAS,INA,42,25,9,5,3,0,5,1,1,0,"['0-0', '1-0', '2-0', '3-0', '4-0', '4-1', '5-...",6.0,5.0,2.0,0.0,"['0-0', '1-0', '2-0', '3-0', '4-0', '5-0', '6-...",NaN,NaN,NaN,NaN,[],7
2,PRINCESS SIRIVANNAVARI Thailand Masters 2018,Bangkok,Thailand,09-01-2018,HSBC BWF World Tour Super 300,MS,Qualification round of 16,1,3,False,21-16,8-21,23-21,Mek Narongrit,Yee Han Chong,THA,MAS,52,58,4,7,6,1,4,4,2,0,"['0-0', '1-0', '2-0', '2-1', '3-1', '4-1', '5-...",2.0,6.0,0.0,1.0,"['0-0', '0-1', '0-2', '0-3', '1-3', '2-3', '2-...",4.0,7.0,4.0,0.0,"['0-0', '1-0', '2-0', '3-0', '4-0', '4-1', '4-...",7
3,PRINCESS SIRIVANNAVARI Thailand Masters 2018,Bangkok,Thailand,09-01-2018,HSBC BWF World Tour Super 300,MS,Qualification round of 16,1,2,False,21-17,21-7,NaN,Mithun Manjunath,Henrikho Kho Wibowo,IND,INA,42,24,14,4,2,0,5,4,1,0,"['0-0', '0-1', '1-1', '1-2', '2-2', '3-2', '3-...",12.0,3.0,1.0,0.0,"['0-0', '1-0', '2-0', '3-0', '4-0', '5-0', '6-...",NaN,NaN,NaN,NaN,[],7
4,PRINCESS SIRIVANNAVARI Thailand Masters 2018,Bangkok,Thailand,09-01-2018,HSBC BWF World Tour Super 300,MS,Qualification round of 16,2,2,False,13-21,13-21,NaN,Chirag Sen,Hashiru Shimono,IND,JPN,26,42,4,5,0,3,4,5,0,1,"['0-0', '1-0', '2-0', '2-1', '2-2', '2-3', '3-...",3.0,4.0,0.0,2.0,"['0-0', '1-0', '2-0', '3-0', '3-1', '4-1', '4-...",NaN,NaN,NaN,NaN,[],7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3756,Orleans Masters 2021 (New Dates),Orleans,France,26-03-2021,BWF Tour Super 100,MS,Quarter final,2,2,False,11-21,15-21,NaN,Ditlev Jaeger Holm,Hans-Kristian Solberg Vittinghus,DEN,DEN,26,42,4,8,0,7,2,6,0,2,"['0-0', '0-1', '1-1', '1-2', '1-3', '1-4', '1-...",4.0,8.0,0.0,5.0,"['0-0', '1-0', '2-0', '2-1', '3-1', '3-2', '3-...",NaN,NaN,NaN,NaN,[],3
3757,Orleans Masters 2021 (New Dates),Orleans,France,26-03-2021,BWF Tour Super 100,MS,Quarter final,1,2,False,21-14,21-10,NaN,Mads Christophersen,Joran Kweekel,DEN,NED,42,24,8,5,2,0,5,5,1,0,"['0-0', '1-0', '1-1', '2-1', '3-1', '4-1', '4-...",6.0,3.0,1.0,0.0,"['0-0', '1-0', '2-0', '3-0', '3-1', '4-1', '5-...",NaN,NaN,NaN,NaN,[],3
3758,Orleans Masters 2021 (New Dates),Orleans,France,27-03-2021,BWF Tour Super 100,MS,Semi final,1,3,False,21-17,9-21,21-11,Toma Junior Popov,Kunlavut Vitidsarn,FRA,THA,51,49,6,6,4,1,5,4,3,0,"['0-0', '0-1', '0-2', '0-3', '0-4', '1-4', '2-...",4.0,6.0,0.0,1.0,"['0-0', '1-0', '1-1', '1-2', '2-2', '2-3', '2-...",6.0,2.0,1.0,0.0,"['0-0', '1-0', '1-1', '2-1', '3-1', '4-1', '4-...",2
3759,Orleans Masters 2021 (New Dates),Orleans,France,27-03-2021,BWF Tour Super 100,MS,Semi final,2,3,False,22-20,13-21,12-21,Hans-Kristian Solberg Vittinghus,Mads Christophersen,DEN,DEN,47,62,6,6,1,4,3,5,1,1,"['0-0', '1-0', '2-0', '2-1', '3-1', '4-1', '4-...",3.0,5.0,0.0,1.0,"['0-0', '1-0', '2-0', '3-0', '3-1', '3-2', '3-...",4.0,6.0,0.0,2.0,"['0-0', '1-0', '2-0', '3-0', '4-0', '4-1', '4-...",2
3760,Orleans Masters 2021 (New Dates),Orleans,France,28-03-2021,BWF Tour Super 100,MS,Final,1,2,False,23-21,21-13,NaN,Toma Junior Popov,Mads Christophersen,FRA,DEN,44,34,4,5,4,2,3,5,2,2,"['0-0', '0-1', '1-1', '2-1', '2-2', '2-3', '3-...",4.0,3.0,2.0,0.0,"['0-0', '0-1', '1-1', '2-1', '2-2', '3-2', '4-...",NaN,NaN,NaN,NaN,[],1

In [ ]:
# Build the structure for the a new data frame (cross-sectional for Linear regression modeling)

# the amount of different variation based on Player name needing to be a key and winner becoming the target to the data are as follows:
## winner x 3 | ( team_one_players x 2 | team_two_players x 2) = n = 12

# fill empty values in game_x_score
df[['game_1_score', 'game_2_score', 'game_3_score']] = df[['game_1_score', 'game_2_score', 'game_3_score']].fillna(value = '0-0')
# split the game_x_score columns by '-' example: game_2_score '21-12' team_one_game_2_score '21' team_two_game_2_score '12'
df[['team_one_game_1_score', 'team_two_game_1_score']] = df.game_1_score.str.split('-',expand=True)
df[['team_one_game_2_score', 'team_two_game_2_score']] = df.game_2_score.str.split('-',expand=True)
df[['team_one_game_3_score', 'team_two_game_3_score']] = df.game_3_score.str.split('-',expand=True)

# Variation 1 winner = 1 target name in team_one_players column (pick up player 1 matches won)
var_1 = df[df['winner'] == 1]
dict = {'team_one_players' : 'player_name',
        'team_one_game_1_score' : 'game_1_points_won' ,
        'team_one_game_2_score' : 'game_2_points_won' ,
        'team_one_game_3_score' : 'game_3_points_won' ,
        'team_two_game_1_score' : 'game_1_points_lost',
        'team_two_game_2_score' : 'game_2_points_lost',
        'team_two_game_3_score' : 'game_3_points_lost'}
var_1.rename(columns=dict, inplace=True)
print(f"var_1 {var_1.shape}")

# Variation 2 winner = 2 target name team_two_player (pick up player 2 matches won)
var_2 = df[df['winner'] == 2]
dict = {'team_two_players' : 'player_name',
        'team_two_game_1_score' : 'game_1_points_won' ,
        'team_two_game_2_score' : 'game_2_points_won' ,
        'team_two_game_3_score' : 'game_3_points_won' ,
        'team_one_game_1_score' : 'game_1_points_lost',
        'team_one_game_2_score' : 'game_2_points_lost',
        'team_one_game_3_score' : 'game_3_points_lost'}
var_2.rename(columns=dict, inplace=True)
print(f"var_2 {var_2.shape}")

# Variation 3 winner = 2 target name team_one_player (pick up player 1 matches lost)
var_3 = df[df['winner'] == 2]
dict = {'team_one_players' : 'player_name',
        'team_two_game_1_score' : 'game_1_points_won' ,
        'team_two_game_2_score' : 'game_2_points_won' ,
        'team_two_game_3_score' : 'game_3_points_won' ,
        'team_one_game_1_score' : 'game_1_points_lost',
        'team_one_game_2_score' : 'game_2_points_lost',
        'team_one_game_3_score' : 'game_3_points_lost'}
var_3.rename(columns=dict, inplace=True)
print(f"var_3 {var_3.shape}")

# Variation 4 winner = 1 target name team_two_player (pick up player 2 matches lost)
var_4 = df[df['winner'] == 1]
dict = {'team_two_players' : 'player_name',
        'team_one_game_1_score' : 'game_1_points_won' ,
        'team_one_game_2_score' : 'game_2_points_won' ,
        'team_one_game_3_score' : 'game_3_points_won' ,
        'team_two_game_1_score' : 'game_1_points_lost',
        'team_two_game_2_score' : 'game_2_points_lost',
        'team_two_game_3_score' : 'game_3_points_lost'}
var_4.rename(columns=dict, inplace=True)
print(f"var_4 {var_4.shape}")

# Variation 5 Handling the walkovers/bye rounds winner = 0
var_5 = df[df['winner'] == 0]
# If winner = 0 then search for team_one or team_two in next rank of tournament (current round_rank - 1) filter same tournament current round_rank - 1)

for x in 


print(f"var_5 {var_5.shape}")
# union the df to create the cross sectional dataset
cs_df = pd.concat([var_1, var_2, var_3, var_4, var_5])
print(f"cs_df {cs_df.shape}")
cs_df

var_1 (1892, 45)
var_2 (1799, 45)
var_3 (1799, 45)
var_4 (1892, 45)
var_5 (70, 45)
cs_df (7452, 52)

,tournament,city,country,date,tournament_type,discipline,round,winner,nb_sets,retired,game_1_score,game_2_score,game_3_score,player_name,team_two_players,team_one_nationalities,team_two_nationalities,team_one_total_points,team_two_total_points,team_one_most_consecutive_points,team_two_most_consecutive_points,team_one_game_points,team_two_game_points,team_one_most_consecutive_points_game_1,team_two_most_consecutive_points_game_1,team_one_game_points_game_1,team_two_game_points_game_1,game_1_scores,team_one_most_consecutive_points_game_2,team_two_most_consecutive_points_game_2,team_one_game_points_game_2,team_two_game_points_game_2,game_2_scores,team_one_most_consecutive_points_game_3,team_two_most_consecutive_points_game_3,team_one_game_points_game_3,team_two_game_points_game_3,game_3_scores,round_rank,game_1_points_won,game_1_points_lost,game_2_points_won,game_2_points_lost,game_3_points_won,game_3_points_lost,team_one_players,team_one_game_1_score,team_two_game_1_score,team_one_game_2_score,team_two_game_2_score,team_one_game_3_score,team_two_game_3_score
0,PRINCESS SIRIVANNAVARI Thailand Masters 2018,Bangkok,Thailand,09-01-2018,HSBC BWF World Tour Super 300,MS,Qualification round of 16,1,3,False,11-21,21-18,21-9,Jun Hao Leong,Kantawat Leelavechabutr,MAS,THA,53,48,8,9,5,1,3,9,0,1,"['0-0', '1-0', '2-0', '3-0', '3-1', '4-1', '4-...",4.0,4.0,2.0,0.0,"['0-0', '0-1', '1-1', '1-2', '2-2', '2-3', '3-...",8.0,2.0,3.0,0.0,"['0-0', '1-0', '1-1', '2-1', '3-1', '4-1', '4-...",7,11,21,21,18,21,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,PRINCESS SIRIVANNAVARI Thailand Masters 2018,Bangkok,Thailand,09-01-2018,HSBC BWF World Tour Super 300,MS,Qualification round of 16,1,2,False,21-7,21-18,0-0,Teck Zhi Soo,Chico Aura Dwi Wardoyo,MAS,INA,42,25,9,5,3,0,5,1,1,0,"['0-0', '1-0', '2-0', '3-0', '4-0', '4-1', '5-...",6.0,5.0,2.0,0.0,"['0-0', '1-0', '2-0', '3-0', '4-0', '5-0', '6-...",NaN,NaN,NaN,NaN,[],7,21,7,21,18,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PRINCESS SIRIVANNAVARI Thailand Masters 2018,Bangkok,Thailand,09-01-2018,HSBC BWF World Tour Super 300,MS,Qualification round of 16,1,3,False,21-16,8-21,23-21,Mek Narongrit,Yee Han Chong,THA,MAS,52,58,4,7,6,1,4,4,2,0,"['0-0', '1-0', '2-0', '2-1', '3-1', '4-1', '5-...",2.0,6.0,0.0,1.0,"['0-0', '0-1', '0-2', '0-3', '1-3', '2-3', '2-...",4.0,7.0,4.0,0.0,"['0-0', '1-0', '2-0', '3-0', '4-0', '4-1', '4-...",7,21,16,8,21,23,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PRINCESS SIRIVANNAVARI Thailand Masters 2018,Bangkok,Thailand,09-01-2018,HSBC BWF World Tour Super 300,MS,Qualification round of 16,1,2,False,21-17,21-7,0-0,Mithun Manjunath,Henrikho Kho Wibowo,IND,INA,42,24,14,4,2,0,5,4,1,0,"['0-0', '0-1', '1-1', '1-2', '2-2', '3-2', '3-...",12.0,3.0,1.0,0.0,"['0-0', '1-0', '2-0', '3-0', '4-0', '5-0', '6-...",NaN,NaN,NaN,NaN,[],7,21,17,21,7,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,PRINCESS SIRIVANNAVARI Thailand Masters 2018,Bangkok,Thailand,09-01-2018,HSBC BWF World Tour Super 300,MS,Qualification round of 16,1,3,False,18-21,21-15,21-17,Dionysius Hayom Rumbaka,Korakrit Laotrakul,INA,THA,60,53,6,4,5,4,3,4,0,4,"['0-0', '0-1', '0-2', '0-3', '1-3', '2-3', '2-...",6.0,3.0,3.0,0.0,"['0-0', '0-1', '1-1', '1-2', '1-3', '1-4', '2-...",3.0,3.0,2.0,0.0,"['0-0', '1-0', '2-0', '2-1', '3-1', '4-1', '5-...",7,18,21,21,15,21,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3429,Barcelona Spain Masters 2020,Barcelona,Spain,19-02-2020,HSBC BWF World Tour Super 300,MS,Round of 32,0,3,True,9-21,21-18,14-12,NaN,Kashyap Parupalli,BRA,IND,44,51,5,7,1,1,2,7,0,1,"['0-0', '0-1', '0-2', '0-3', '0-4', '1-4', '1-...",5.0,3.0,1.0,0.0,"['0-0', '1-0', '1-1', '2-1', '3-1', '3-2', '3-...",NaN,NaN,NaN,NaN,[],5,NaN,NaN,NaN,NaN,NaN,NaN,Ygor Coelho,9,21,21,18,14,12
3464,YONEX All England Open 2020,Birmingham,England,11-03-2020,HSBC BWF World Tour Super 1000,MS,Round of 32,0,1,True,3-0,0-0,0-0,NaN,Kashyap Parupalli,INA,IND,3,0,3,0,0,0,3,0,0,0,"['0-0', '1-0', '2-0', '3-0']",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,Shesar Hiren Rhustavito,3,0,0,0,0,0
3483,YONEX All England Open 2020,Birmingham,England,14-03-2020,HSBC BWF World Tour Super 1000,MS,Semi final,0,1,True,17-14,0-0,0-0,NaN,Anders Antonsen,TPE,DEN,17,14,6,2,0,0,6,2,0,0,"['0-0', '0-1', '1-1', '2-1', '3-1', '4-1', '5-...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,Tien Chen Chou,17,14,0,0,0,0
3572,YONEX Thailand Open,Bangkok,Thailand,13-01-2021,HSBC BWF World Tour Super 1000,MS,Round of 32,0,3,True,9-21,21-13,8-14,NaN,Jason Anthony Ho-Shue,IND,CAN,38,48,6,6,1,1,2,6,0,1,"['0-0', '0-1', '0-2', '0-3', '1-3', '2-3', '2-...",6.0,3.0,1.0,0.0,"['0-0', '1-0', '2-0', '3-0', '3-1', '4-1', '4-...",NaN,NaN,NaN,NaN,[],5,NaN,NaN,NaN,NaN,NaN,NaN,Kashyap Parupalli,9,21,21,13,8,14
3594,TOYOTA Thailand Open,Bangkok,Thailand,19-01-2021,HSBC BWF World Tour Super 1000,MS,Round of 32,0,1,True,0-3,0-0,0-0,NaN,Rasmus Gemke,IND,DEN,0,3,0,3,0,0,0,3,0,0,"['0-0', '0-1', '0-2', '0-3']",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,Kashyap Parupalli,0,3,0,0,0,0

In [489]:
# count nan in each column
df.isna().sum()

tournament                                    0
city                                          0
country                                       0
date                                          0
tournament_type                               0
discipline                                    0
round                                         0
winner                                        0
nb_sets                                       0
retired                                       0
game_1_score                                  0
game_2_score                                  0
game_3_score                                  0
team_one_players                              0
team_two_players                              0
team_one_nationalities                        0
team_two_nationalities                        0
team_one_total_points                         0
team_two_total_points                         0
team_one_most_consecutive_points              0
team_two_most_consecutive_points              0
team_one_game_points                          0
team_two_game_points                          0
team_one_most_consecutive_points_game_1       0
team_two_most_consecutive_points_game_1       0
team_one_game_points_game_1                   0
team_two_game_points_game_1                   0
game_1_scores                                 0
team_one_most_consecutive_points_game_2      38
team_two_most_consecutive_points_game_2      38
team_one_game_points_game_2                  38
team_two_game_points_game_2                  38
game_2_scores                                29
team_one_most_consecutive_points_game_3    2459
team_two_most_consecutive_points_game_3    2459
team_one_game_points_game_3                2459
team_two_game_points_game_3                2459
game_3_scores                                38
round_rank                                    0
team_one_game_1_score                         0
team_two_game_1_score                         0
team_one_game_2_score                         0
team_two_game_2_score                         0
team_one_game_3_score                         0
team_two_game_3_score                         0
dtype: int64

In [490]:
substring = 'Deschamp'

locations = []
for col in df.columns:
    mask = df[col].astype(str).str.contains(substring, case=False, na=False)
    for idx in df[mask].index:
        locations.append((idx, col, df.loc[idx, col]))


print(f"\nSpecific locations of '{substring}':")
for row_idx, col_name, value in locations:
    print(f"Row {row_idx}, Column '{col_name}': {value}")

Specific locations of 'Deschamp':
Row 296, Column 'team_one_players': Jocelyn Deschamp
Row 3696, Column 'team_one_players': Grégoire Deschamp
Row 3708, Column 'team_one_players': Grégoire Deschamp

In [491]:
# list the unique values in tournament_type field

player_names_t1 = df['team_one_players'].unique().tolist()
player_names_t1_count = len(player_names_t1)
print(player_names_t1_count)
player_names_t1

512

['Jun Hao Leong',
 'Teck Zhi Soo',
 'Mek Narongrit',
 'Mithun Manjunath',
 'Chirag Sen',
 'Shreyansh Jaiswal',
 'Duc Phat Le',
 'Dionysius Hayom Rumbaka',
 'Kunlavut Vitidsarn',
 'Tanongsak Saensomboonsuk',
 'Thomas Rouxel',
 'Ygor Coelho',
 'Suppanyu Avihingsanon',
 'Tien Minh Nguyen',
 'Abhishek Yelegar',
 'Yun Hu',
 'Panji Ahmad Maulana',
 'Zulfadli Zulkiffli',
 'Kim Bruun',
 'Daren Liew',
 'Nan Wei',
 'Hashiru Shimono',
 'Misha Zilberman',
 'Pannawit Thongnuam',
 'Lucas Corvee',
 'Cao Cuong Pham',
 'Kantaphon Wangcharoen',
 'Iskandar Zulkarnain',
 'Jason Anthony Ho-Shue',
 'Joo Ven Soong',
 'Sony Dwi Kuncoro',
 'Kashyap Parupalli',
 'Subhankar Dey',
 'Chi Wing Lim',
 'Tien Chen Chou',
 'Emil Holst',
 'Hans-Kristian Solberg Vittinghus',
 'Kazumasa Sakai',
 'Wan Ho Son',
 'Hyeok Jin Jeon',
 'Anthony Sinisuka Ginting',
 'Wei Feng Chong',
 'Dan Lin',
 'Kenta Nishimoto',
 'Yuxiang Huang',
 'Viktor Axelsen',
 'Anders Antonsen',
 'Ihsan Maulana Mustofa',
 'Jonatan Christie',
 'Brice Leverdez',
 'Ka Long Angus Ng',
 'Krishna Adi Nugraha',
 'Shesar Hiren Rhustavito',
 'Vega Vio Nirwanda',
 'Chao Yu Kan',
 'Sameer Verma',
 'Rajiv Ouseph',
 'Kanta Tsuneyama',
 'Wing Ki Vincent Wong',
 'Khosit Phetpradab',
 'Rasmus Gemke',
 'Kartikey Gulshan Kumar',
 'Pratul Joshi',
 'Rahul Yadav Chittaboina',
 'Siddharth Pratap Singh',
 'B. Sai Praneeth',
 'Vladimir Malkov',
 'Junpeng Zhao',
 'Cheuk Yiu Lee',
 'H. S. Prannoy',
 'Sourabh Verma',
 'Tommy Sugiarto',
 'Bin Qiao',
 'Jen Hao Hsu',
 'Tzu Wei Wang',
 'Yuqi Shi',
 'Mathew Fogarty',
 'Yehezkiel Fritz Mainaky',
 'Michael Spencer-Smith',
 'Riichi Takeshita',
 'Søren Toft',
 'R. M. V. Gurusaidutt',
 'Luís Enrique Peñalver',
 'Yuehang Wang',
 'Philip Discher',
 'Joel König',
 'Sitthikom Thammasin',
 'Christian Kirchmayr',
 'Adam Mendrek',
 'Lars Schaenzler',
 'Lucas Claerbout',
 'Zii Jia Lee',
 'Eetu Heino',
 'Kento Momota',
 'Yu Igarashi',
 'Arnaud Merkle',
 'Jan O Jorgensen',
 'Koki Watanabe',
 'Rüdiger Gnedt',
 'Birger Abts',
 'David Peng',
 'Zvonimir Durkinjak',
 'Alexander Roovers',
 'Kalle Koljonen',
 'Hyun Il Lee',
 'Dong Keun Lee',
 'Mark Caljouw',
 'Long Chen',
 'Roman Razaki',
 'Joshua Magee',
 'Valeriy Atrashchenkov',
 'Toma Junior Popov',
 'Aneeth Kumar Repudi',
 'Hugo Jardim',
 'Marc Laporte',
 'Jocelyn Deschamp',
 'Adel Hamek',
 'Jonathan Persson',
 'Pavel Kotsarenko',
 'Bilal Elharab',
 'Hemanth M.Gowda',
 'Kartik Jindal',
 'Valentin Singer',
 'Remi Rossi',
 'Samuel Hsiao',
 'Duarte Nuno Anjo',
 'Henri Aarnio',
 'Milan Dratva',
 'Iikka Heino',
 'Sam Parsons',
 'Kai Schaefer',
 'Romain Frank',
 'Pablo Abian',
 'Victor Svendsen',
 'Wei Chi Liu',
 'Yu Hsien Lin',
 'Saputra Vicky Angga',
 'Yufeng Cao',
 'Jiahao Yu',
 'Zeqi Zhou',
 'Shumin Liu',
 'Zhong Zezhou',
 'Feixiang Sun',
 'Kuei Chun Shih',
 'Haokun Ye',
 'Yun Kyu Lee',
 'Xiang Li',
 'Hongyang Weng',
 'Young Woong Ha',
 'Yu Jen Chi',
 'Haichao Liu',
 'Shifeng Li',
 'Chi Ting Chen',
 'Guangzu Lu',
 'Kwang Hee Heo',
 'Yupeng Bai',
 'Dylan Soedjasa',
 'Yee Han Chong',
 'Anthony Joe',
 'Cham Chen',
 'Pengbo Ren',
 'Pit Seng Low',
 'Kodai Naraoka',
 'Lakshya Sen',
 'Abhinav Manota',
 'Ajay Jayaram',
 'Niluka Karunaratne',
 'Yang Shen',
 'Karan Rajan Rajarajan',
 'Takuma Ueda',
 'June Wei Cheam',
 'Milan Ludik',
 'Antonio Li',
 'Nicholas Bonkowsky',
 'Timothy Chiu',
 'Xiaodong Sheng',
 'Hin Shun Wong',
 'Timothy Lam',
 'Sankeerth B. R.',
 'Mark Shelley Alcala',
 'Phillips Jap',
 'Howard Shu',
 'Toby Penty',
 'Kartikay Tyagi',
 'Seyed Mohammad Hossein Vakili',
 'Bo Zhao',
 'Guoxing Huang',
 'Alexander Bianchini',
 'Kevin Lee',
 'Kok Hong Woon',
 'Phillipe Charron',
 'Imran Wadia',
 'Maxime Tétreault',
 'Mathieu Morneau',
 'Joshua Hurlburt-Yu',
 'Aaron Zhao',
 'Minoru Koga',
 'Kevin Cordon',
 'Max Weisskirchen',
 'Kevin Barkman',
 'Hoang Nam Nguyen',
 'Takuma Obayashi',
 'Chong Wei Lee',
 'Srikanth Kidambi',
 'Kantawat Leelavechabutr',
 'Henrikho Kho Wibowo',
 'Rosario Maddaloni',
 'Zin Rei Ryan Ng',
 'Chia Hung Lu',
 'Adulrach Namkul',
 'Fabio Caponio',
 'Firman Abdul Kholik',
 'Kean Yew Loh',
 'Dmitrii Riabov',
 'Jeffrey Lam',
 'Elias Bracke',
 'Gergely Krausz',
 'Maksim Makalov',
 'Fong Hau Sim',
 'Luka Wraber',
 'Farouk Mohammed Hassan',
 'Ilya Goncharov',
 'Ilya Kamyshenkov',
 'Chun Kar Lung',
 'Satheishtharan Ramachandran',
 'Egor Kurdyukov',
 'Ryotaro Maruo',
 'Vladimir Nikulov',
 'Yin Chak Chan',
 'Chuan-En Hu',
 'Chico Aura Dwi Wardoyo',
 'Seong Hyun Son',
 'Hsuan Yi Hsueh',
 'Muhammad Bayu Pangisthu',
 'Naohiro Matsukawa',
 'Songjian Wu',
 'Naoki Yamazawa',
 'Chih Chieh Yang',
 'Yiming Xu',
 'Chun-Yi Lin',
 'Chia Hao Lee',
 'Batdavaa Munkhbat',
 'Andrew Susanto',
 'Nabin Shrestha',
 'Yu Ming, Adam Lau',
 'Carlo Glenn Remo',
 'Thien Loc Nguyen',
 'Phone Pyae Naing',
 'Saran Jamsri',
 'Thanh Long Truong',
 'Vincent Cheng Wei Phuah',
 'Siril Verma',
 'Yu Leong, Alfred Lau',
 'Fikri Ihsandi Hadmadi',
 'Vijetha N. V. S.',
 'Simon Wang',
 'Seng Zoe Yeoh',
 'Jhotiswaran Karupathevan',
 'Abhishek Yeligar',
 'Giap Chin Goh',
 'Gatjra Piliang Fiqihila Cupu',
 'Eric Jr Timmerman',
 'Alex Alcala Dominguez',
 'Raymond Webster',
 'Rasmus Messerschmidt',
 'Hannes Gerberich',
 'Manuel Vazquez',
 'Alvaro Vazquez',
 'Felix Burestedt',
 'Sarath Dunna',
 'Abhyansh Singh',
 'Ikhsan Leonardo Imanuel Rumbay',
 'Aman Kumar',
 'Ansal Yadav',
 'Sai Charan Koya',
 'Lauhit Pokuri',
 'Eveshgaran Vasigaran',
 'Mayank Ahuja',
 'Balraj Kajla',
 'Abhishek Kulkarni',
 'Sachin Rawat',
 'Anant Shivam Jindal',
 'Arintap Das Gupta',
 'Kaushal Dharmamer',
 'Yash Yogi',
 'Munawar Mohammed',
 'Yun Gyu Lee',
 'Vicky Angga Saputra',
 'Adrian George',
 'Harshit Aggarwal',
 'Aryamann Tandon',
 'Daniel S. Farid',
 'Kevin Arokia Walter',
 'Ferneel Hazael Sompie',
 'Muh. Asqar Harianto',
 'Syahzlan Hazwan Salleh',
 'Putra Suntana',
 'Gilang Abdillah Imaduddin',
 'Riyanto Subagja',
 'Dean Bencha Wijaya',
 'Bagas Kristianto Nugroho',
 'Christian Adinata',
 'Abdul Kadir Zailani',
 'Isna Sakti Maulana Mustaqim Mustaqim',
 'Muh. Azahbru B Karsa',
 'Bobby Setiabudi',
 'Syabda Perkasa Belawa',
 'Muhammad Aldo Apriyandi',
 'Datu Mohd Saffuan Nizam Sardik',
 'Aldo Oktaviano Purnomo',
 'Koji Naito',
 'Misbun Ramdan Mohmed Misbun',
 'Alberto Alvin Yulianto',
 'En Chia Chang',
 'Muhammad Febriansyah',
 'Muhammad Ziyad Md Tah',
 'Zulhelmi Zulkiffli',
 'Ajay Kumar K.',
 'Donghun Kim',
 'Hua Chun Liang',
 'Jaromir Janacek',
 'Dimitar Yanakiev',
 'Jeppe Bruun',
 'Dmytro Zavadsky',
 'Dinuka Karunaratna',
 'Artem Pochtarov',
 'Joonas Korhonen',
 'Muhammed Ali Kurt',
 'Andre Marteen',
 'Ethan Rose',
 'Thomas Fuchs',
 'Julian Edhofer',
 'Cristian Savin',
 'Yann Zaccaria',
 'Artem Serpionov',
 'Harsheel Dani',
 'David Kramer',
 'Wolfgang Gnedt',
 'Jingtong Chen',
 'Jia Wei Tan',
 'Bodhit Joshi',
 'Siddharath Thakur',
 'Georges Julien Paul',
 'Alex Lane',
 'Christopher Kan',
 'Mark Brady',
 'Lukas Zevl',
 'Jonathan Dolan',
 'Christo Popov',
 'Heng Lin Ngan',
 'Christopher Grimley',
 'Johnnie Torjussen',
 'Alex Marritt',
 'Luke Pearce',
 'David Jones',
 'Nhat Nguyen',
 'Matthew Carder',
 'Bernardo Atilano',
 'Ivan Rusev',
 'Nick Fransman',
 'Shiau Cheng Chen',
 'Krzysztof Jakowczuk',
 'Kento MOMOTA',
 'Yuqi SHI',
 'Tien Chen CHOU',
 'Tommy SUGIARTO',
 'Wan Ho SON',
 'Kantaphon WANGCHAROEN',
 'Maxime Moreels',
 'Armand Rodriguez',
 'Mohamed Abderrahime Belarbi',
 'Ade Resky Dwicahyo',
 'Emre Lale',
 'Masashi Nishino',
 'Junfeng Gu',
 'Geonyeop Cho',
 'Lanxi Lei',
 'Yunze Li',
 'Sheng Po Yu',
 'Korakrit Laotrakul',
 'Zhengze Gao',
 'Jhonatan Wu Zheng',
 'Kaian Wu',
 'Xujun Chen',
 'Namboun Luangamath',
 'Chengming Ren',
 'Weiyi Zhang',
 'Yang Yang',
 'Ping-Hsien Huang',
 'Tobias Kuenzi',
 'Raul Must',
 'Luka Milic',
 'Jan Louda',
 'Azmy Qowimuramadhoni',
 'Karono Karono',
 'Collins Valentine Filimon',
 'Adrian Dziolko',
 'Sergey Sirant',
 'Daniel Nikolov',
 'Siddharth .',
 'Gurpartap Singh Dhaliwal',
 'Hardik Makkar',
 'Peter Yan',
 'Mateja Manic',
 'Steffen Rasmussen',
 'Yunzhi Chen',
 'Pranav Srikanth',
 'Miklos Kanyasi',
 'Adwin Lau',
 'Brian Yang',
 'Yen-Yu Lee',
 'Xavier Laperriere',
 'Hai Chao Liu',
 'Lan Xi Lei',
 'Peng Bo Ren',
 'Shi Feng Li',
 'Fei Xiang Sun',
 'Hong Yang Weng',
 'Vinson Chiu',
 'Cesar Adonis Brito Gonzalez',
 'Nicholas Robert Henson Waller',
 'Yu Xiang Huang',
 'Runze Yan',
 'Vladimir Shipilenko',
 'Dmitrii Klimenko',
 'Miha Ivanič',
 'Matvei Manuylov',
 'Alexey Panov',
 'Georgii Karpov',
 'Artyom Savatyugin',
 'Dai Watanabe',
 'Amrullo Bakhshullaev',
 'Vinh Quang Ho Nguyen',
 'Kiran George',
 'Orijit Chaliha',
 'Siddharth Jakhar',
 'Yu Peng Bai',
 'Rishabh Deshpande',
 'Kittipong Imnark',
 'Talar Laa',
 'Rahul Bharadwaj B.M',
 'Shota Omoto',
 'Yusuke Onodera',
 'Li Yang Su',
 'Pang Fong Pui',
 'Thu Thao Nguyen',
 'Hai Dang Nguyen',
 'Phakorn Chotphinit',
 'Jun Yan Ng',
 'Chien-Wei Chiang',
 'Md Tah M Ziyad',
 'Guang Zu Lu',
 'Chia Hsuan Lin',
 'Kar Lung Chun',
 'Ze Qi Zhou',
 'Jun Peng Zhao',
 'Muhammad Farhan Ananto',
 'M. Enrico Giralda Harsari',
 'Aaron Sangga Wijaya',
 'Muhammad Syafiq Iqbal Mohd Nadzri',
 'Classius Chris Belandro',
 'Novian Harya Pratama',
 'Gabriel Evan Santoso',
 'Wisnu Yuli Prasetyo',
 'Muhammad Akhdan Widjanarko',
 'Jovi Mikhael',
 'Datu Mohd Shah Eizlan Sardik',
 'Jia Wei Joel Koh',
 'Handoko Yusuf Wijayanto',
 'Aram Mahmoud',
 'B.M.Rahul Bharadwaj',
 'Joran Kweekel',
 'Jacob Nilsson',
 'Leo Rossi',
 'Robert Mann',
 'Binghong Ye',
 'Yu Qi Shi',
 'Innocenzo Santoro',
 'Felix Kruchten',
 'Tobias Mund',
 'David Kim',
 'Felix Hammes',
 'Jonas Scheller',
 'Ansgar Kirste',
 'Christopher Klauer',
 'Lukas Resch',
 'Brian Holtschke',
 'Raghu Mariswamy',
 'Alap Mishra',
 'Ivan Valenzuela',
 'Sergi Alcala',
 'Jofre Comella',
 'Oriol Altimira',
 'Leon Seiwald',
 'Mads Christophersen',
 'Amaury Lievre',
 'Harry Huang',
 'Grégoire Deschamp',
 'Yanis Gaudin',
 'Simon Baron-Vezilier',
 'Philip Illum Klindt',
 'Koceila Mammeri',
 'Iliyan Stoynov',
 'Mads Thøgersen',
 'Youcef Sabri Medel',
 'Enogat Roy',
 'Martin Bundgaard',
 'Ditlev Jaeger Holm',
 'Magnus Johannesen',
 'Lino Munoz',
 'Julien Carraggi',
 'Thomas Fourcade']

In [492]:
player_names_t2 = df['team_two_players'].unique().tolist()
player_names_t2_count = len(player_names_t2)
print(player_names_t2_count)
player_names_t2

497

['Kantawat Leelavechabutr',
 'Chico Aura Dwi Wardoyo',
 'Yee Han Chong',
 'Henrikho Kho Wibowo',
 'Hashiru Shimono',
 'Fikri Ihsandi Hadmadi',
 'Kunlavut Vitidsarn',
 'Korakrit Laotrakul',
 'Jun Hao Leong',
 'Dionysius Hayom Rumbaka',
 'Kantaphon Wangcharoen',
 'Cao Cuong Pham',
 'Cheuk Yiu Lee',
 'Jason Anthony Ho-Shue',
 'Ihsan Maulana Mustofa',
 'Shesar Hiren Rhustavito',
 'Sitthikom Thammasin',
 'Firman Abdul Kholik',
 'Khosit Phetpradab',
 'Adulrach Namkul',
 'Karan Rajan Rajarajan',
 'Jia Wei Tan',
 'Tommy Sugiarto',
 'Panji Ahmad Maulana',
 'Suppanyu Avihingsanon',
 'Daren Liew',
 'Misha Zilberman',
 'Lucas Corvee',
 'Thomas Rouxel',
 'Joo Ven Soong',
 'Kim Bruun',
 'June Wei Cheam',
 'Jonatan Christie',
 'Zii Jia Lee',
 'Wing Ki Vincent Wong',
 'Tzu Wei Wang',
 'Long Chen',
 'Anders Antonsen',
 'Ka Long Angus Ng',
 'Brice Leverdez',
 'Ygor Coelho',
 'Chong Wei Lee',
 'Rasmus Gemke',
 'Hyun Il Lee',
 'B. Sai Praneeth',
 'Anthony Sinisuka Ginting',
 'Hyeok Jin Jeon',
 'Kenta Nishimoto',
 'Saputra Vicky Angga',
 'Enzi Shafira',
 'Subhankar Dey',
 'Abhishek Yelegar',
 'Sony Dwi Kuncoro',
 'Jen Hao Hsu',
 'Kazumasa Sakai',
 'Dan Lin',
 'Emil Holst',
 'Yuxiang Huang',
 'Tien Chen Chou',
 'Hans-Kristian Solberg Vittinghus',
 'Kashyap Parupalli',
 'Wei Feng Chong',
 'Wan Ho Son',
 'Siril Verma',
 'Bodhit Joshi',
 'Siddharth Pratap Singh',
 'Iskandar Zulkarnain',
 'Daniel S. Farid',
 'Ajay Kumar K.',
 'Rahul Yadav Chittaboina',
 'Rajiv Ouseph',
 'Yun Hu',
 'Nan Wei',
 'Srikanth Kidambi',
 'Shreyansh Jaiswal',
 'Yuqi Shi',
 'Ajay Jayaram',
 'Kartikey Gulshan Kumar',
 'Sameer Verma',
 'Bin Qiao',
 'Philip Discher',
 'Lars Schaenzler',
 'Joel König',
 'Michal Rogalski',
 'Alexander Roovers',
 'Jan Frohlich',
 'Yusuke Onodera',
 'Arnaud Merkle',
 'Riichi Takeshita',
 'R. M. V. Gurusaidutt',
 'Takuma Ueda',
 'Kai Schaefer',
 'Kento Momota',
 'Mark Caljouw',
 'Yu Igarashi',
 'Koki Watanabe',
 'Jan O Jorgensen',
 'Kalle Koljonen',
 'Alex Vlaar',
 'Søren Toft',
 'Wolfgang Gnedt',
 'Dmytro Zavadsky',
 'Chao Yu Kan',
 'Valeriy Atrashchenkov',
 'Junpeng Zhao',
 'Zvonimir Durkinjak',
 'Pablo Abian',
 'Kanta Tsuneyama',
 'Tanongsak Saensomboonsuk',
 'Dong Keun Lee',
 'H. S. Prannoy',
 'Romain Frank',
 'Alexis Chollet',
 'Anant Shivam Jindal',
 'Bernardo Atilano',
 'Samuel Hsiao',
 'Shinsai Deslauriers',
 'Remi Rossi',
 'Hardik Makkar',
 'Raymond Webster',
 'Adrian George',
 'Max Weisskirchen',
 'Valentin Singer',
 'Mohamed Abderrahime Belarbi',
 'Michael Spencer-Smith',
 'Hemanth M.Gowda',
 'Aneeth Kumar Repudi',
 'Leo Rossi',
 'Abhishek Yeligar',
 'Adam Mendrek',
 'Sergey Sirant',
 'Nhat Nguyen',
 'Vladimir Malkov',
 'Sam Parsons',
 'Eetu Heino',
 'Milan Ludik',
 'Artem Pochtarov',
 'Rosario Maddaloni',
 'Joshua Magee',
 'Iikka Heino',
 'Lucas Claerbout',
 'Sahil Sipani',
 'Victor Svendsen',
 'Pengbo Ren',
 'Chia Hung Lu',
 'Yu Jen Chi',
 'Seong Hyun Son',
 'Qin Zheng',
 'Chih Chieh Yang',
 'Shifeng Li',
 'Haichao Liu',
 'Chi Ting Chen',
 'Guangzu Lu',
 'Kwang Hee Heo',
 'Yu Hsien Lin',
 'Yufeng Cao',
 'Zeqi Zhou',
 'Shumin Liu',
 'Pannawit Thongnuam',
 'Andre Marteen',
 'Chengming Ren',
 'Tien Minh Nguyen',
 'Chia Hao Lee',
 'Hongyang Weng',
 'Feixiang Sun',
 'Kodai Naraoka',
 'Robert Mann',
 'Oscar Guo',
 'Anthony Joe',
 'Niluka Karunaratne',
 'Abhinav Manota',
 'Lakshya Sen',
 'Cham Chen',
 'De Jun Jackie Tan',
 'Dimitri Han',
 'Peter Yan',
 'Pit Seng Low',
 'Sourabh Verma',
 'Yehezkiel Fritz Mainaky',
 'Sankeerth B. R.',
 'Howard Shu',
 'Mark Shelley Alcala',
 'Grimaldy Navirio Gunawan',
 'Phillips Jap',
 'Yun Kyu Lee',
 'Xiaodong Sheng',
 'Fabian Roth',
 'Jacob Nilsson',
 'Joshua Hurlburt-Yu',
 'Johnathan Akin-Mulrooney',
 'Niccolo Tagle',
 'Minoru Koga',
 'Carlo Glenn Remo',
 'Anthony Nguyen',
 'Takuma Obayashi',
 'Bao Duc Duong',
 'Enrico Asuncion',
 'Minh Bao',
 'Guoxing Huang',
 'Kevin Lee',
 'Andrew Zhuang',
 'Timothy Lam',
 'Antonio Li',
 'Mathieu Morneau',
 'Imran Wadia',
 'Toby Penty',
 'Fabio Caponio',
 'Kean Yew Loh',
 'Hin Shun Wong',
 'Pratul Joshi',
 'Mithun Manjunath',
 'Koji Naito',
 'Alexey Panov',
 'Ilya Kamyshenkov',
 'Chun Kar Lung',
 'Artem Serpionov',
 'Vladimir Nikulov',
 'Luka Wraber',
 'Chirag Sen',
 'Nikita Fedotovskikh',
 'Dmitrii Riabov',
 'Matvei Manuylov',
 'Satheishtharan Ramachandran',
 'Ryotaro Maruo',
 'Yusei Baba',
 'Donghun Kim',
 'Vicky Angga Saputra',
 'Ratnajit Tamang',
 'Hsuan Yi Hsueh',
 'Ching Wei Chen',
 'Simon Wang',
 'Jhotiswaran Karupathevan',
 'Vijetha N. V. S.',
 'Gatjra Piliang Fiqihila Cupu',
 'Seng Zoe Yeoh',
 'Faiz Rozain',
 'En Chia Chang',
 'Yu-Hua Lai',
 'Chun-Yi Lin',
 'Thu Thao Nguyen',
 'Muhammad Bayu Pangisthu',
 'Kuei Chun Shih',
 'Siddharath Thakur',
 'Saran Jamsri',
 'Georges Julien Paul',
 'Zin Rei Ryan Ng',
 'Chia Hsuan Lin',
 'Daniel Fan',
 'Hannes Gerberich',
 'Alvaro Vazquez',
 'Kari Gunnarsson',
 'Armand Rodriguez',
 'Manuel Vazquez',
 'Christo Popov',
 'Rasmus Messerschmidt',
 'Raul Must',
 'Toma Junior Popov',
 'Karan Choudhary',
 'Alap Mishra',
 'Raghu Mariswamy',
 'Yin Chak Chan',
 'Munawar Mohammed',
 'Siddharth .',
 'Yash Yogi',
 'Rajat Rathore',
 'Manish Gupta',
 'Ameya Oak',
 'Kaushal Dharmamer',
 'Arintap Das Gupta',
 'Eveshgaran Vasigaran',
 'Balraj Kajla',
 'Kartik Jindal',
 'Kanishq M',
 'Aditya Joshi',
 'Yun Gyu Lee',
 'Harshit Aggarwal',
 'Giap Chin Goh',
 'Lauhit Pokuri',
 'Kevin Arokia Walter',
 'Chi Wing Lim',
 'Herdian Muhamad Labib',
 'Bobby Setiabudi',
 'Muhammad Rehan Diaz',
 'Muhammad Aldo Apriyandi',
 'Datu Mohd Saffuan Nizam Sardik',
 'Daniel Hardiana Octavianus',
 'Muhammad Febriansyah',
 'Farid Pramadita Gunawan',
 'Yonathan Ramlie',
 'Hong Wei Ye',
 'Auditya Alpha Hidayat',
 'Aldy Firmanda',
 'Andrew Susanto',
 'Syabda Perkasa Belawa',
 'Christian Adinata',
 'Rezha Akbar Raja Husain',
 'Abdul Kadir Zailani',
 'Isna Sakti Maulana Mustaqim Mustaqim',
 'Karono Karono',
 'Muhammad Izzuddin Shamsul Muzli',
 'Hua Chun Liang',
 'Riyanto Subagja',
 'Handoko Yusuf Wijayanto',
 'Ikhsan Leonardo Imanuel Rumbay',
 'Bagas Kristianto Nugroho',
 'Nyoman Tryadnya Arya Kurniawan',
 'Krishna Adi Nugraha',
 'Young Woong Ha',
 'Seung Hoon Lee',
 'Li Yang Su',
 'Chuan-En Hu',
 'Joonas Korhonen',
 'Birger Abts',
 'Joran Kweekel',
 'Maxime Moreels',
 'Emre Lale',
 'Henri Aarnio',
 'Gergely Krausz',
 'Nick Fransman',
 'Milan Dratva',
 'Muhammed Ali Kurt',
 'Pang Fong Pui',
 'David Kramer',
 'Mike Vallenthini',
 'Rüdiger Gnedt',
 'Yann Zaccaria',
 'Elias Bracke',
 'Collins Valentine Filimon',
 'Christian Kirchmayr',
 'Jaromir Janacek',
 'Harsheel Dani',
 'Shi Hang (Stephen) Lai',
 'Abhyansh Singh',
 'Felix Burestedt',
 'Ciar Pringle',
 'Jack Macgregor',
 'Ethan Rose',
 'Adam Lam',
 'Zach Russ',
 'Albin Carl Hjelm',
 'Andy Tsai',
 'Hugo Jardim',
 'Lukas Zevl',
 'Dimitar Yanakiev',
 'Ben Torrance',
 'Christopher Grimley',
 'David Jones',
 'Vinson Chiu',
 'Johnnie Torjussen',
 'Duarte Nuno Anjo',
 'Alex Lane',
 'Cristian Savin',
 'Jong Woo Yim',
 'Sameer VERMA',
 'Wan Ho SON',
 'Anthony Sinisuka GINTING',
 'Kantaphon WANGCHAROEN',
 'Yuqi SHI',
 'Tommy SUGIARTO',
 'Kento MOMOTA',
 'Viktor Axelsen',
 'Yuehang Wang',
 'Bernat Amaya',
 'Pavel Kotsarenko',
 'Adel Hamek',
 'Liang Liu',
 'Ping-Hsien Huang',
 'Weiyi Zhang',
 'Dewei Liu',
 'Bingyuan Li',
 'Kaian Wu',
 'Zhengxing Wang',
 'Xujun Chen',
 'Geonyeop Cho',
 'Binghong Ye',
 'Jingtong Chen',
 'Kuan-Ting Lin',
 'Xiang Li',
 'Wei Chi Liu',
 'Yang Yang',
 'Yen Chun Chen',
 'Batdavaa Munkhbat',
 'Lanxi Lei',
 'Shiau Cheng Chen',
 'Farouk Mohammed Hassan',
 'Zhengze Gao',
 'Daniel Nikolov',
 'Julien Carraggi',
 'Ivan Rusev',
 'Teck Zhi Soo',
 'Luís Enrique Peñalver',
 'Satinder Malik',
 'Patrick Bjerregaard',
 'Eason Wong',
 'Xavier Laperriere',
 'Lan Xi Lei',
 'Alexander Bianchini',
 'Seyed Mohammad Hossein Vakili',
 'Sheng Po Yu',
 'Mateja Manic',
 'Mathew Fogarty',
 'Shi Feng Li',
 'Lino Munoz',
 'Hai Chao Liu',
 'Ze Qi Zhou',
 'Kevin Barkman',
 'Hong Yang Weng',
 'Peng Bo Ren',
 'Fei Xiang Sun',
 'Brian Yang',
 'Guang Zu Lu',
 'Yu Xiang Huang',
 'Yu Qi Shi',
 'Gabriel Ma',
 'Ilya Goncharov',
 'Vinh Quang Ho Nguyen',
 'Maksim Makalov',
 'Amrullo Bakhshullaev',
 'Runze Yan',
 'Dmitrii Klimenko',
 'Vladimir Shipilenko',
 'Chi Ming Wong',
 'Anton Ivanov',
 'Anton Derbenev',
 'Dai Watanabe',
 'Jun Peng Zhao',
 'Kittipong Imnark',
 'Rahul Bharadwaj B.M',
 'Gurpartap Singh Dhaliwal',
 'Phakorn Chotphinit',
 'Aryamann Tandon',
 'Orijit Chaliha',
 'Yu Peng Bai',
 'Kenta Matsumura',
 'Yosei Yamaguchi',
 'Ji Hoon Choi',
 'Kee Liang Lau',
 'Shota Omoto',
 'Jeffrey Lam',
 'Jia Wei Joel Koh',
 'Alberto Alvin Yulianto',
 'Syahzlan Hazwan Salleh',
 'Thuan Kim',
 'Chacharit Yaowanit',
 'Teerapat Kleawan',
 'Praranat Praputtham',
 'Tien Tuan Nguyen',
 'Jun Yan Ng',
 'Hai Dang Nguyen',
 'Miha Ivanič',
 'Mochamad Ryan Bintang Pradana',
 'Muhammad Hafid Hendarto',
 'Ferneel Hazael Sompie',
 'Muh. Asqar Harianto',
 'Muh. Azahbru B Kasra',
 'Datu Mohd Shah Eizlan Sardik',
 'Moch Fairuzzani Wahbatul Bida',
 'Galih Prasetyo Utomo',
 'Diviana Arya Ramanda Putra',
 'Dimas Setiawan',
 'Aldo Oktaviano Purnomo',
 'Wisnu Yuli Prasetyo',
 'Kar Lung Chun',
 'Ade Resky Dwicahyo',
 'Jovi Mikhael',
 'Azmy Qowimuramadhoni',
 'Kiran George',
 'Soren Opti',
 'Jeppe Bruun',
 'B.M.Rahul Bharadwaj',
 'Osleni Guerrero',
 'Aidil Sholeh Ali Sadikin',
 'Jonas Scheller',
 'Brian Holtschke',
 'Christopher Klauer',
 'Mattias Sonderskov',
 'Jakob Godt',
 'Artyom Savatyugin',
 'Rowan Scheurkogel',
 'Ansal Yadav',
 'Ching-Sheng Chang',
 'Oriol Altimira',
 'Martin Bundgaard',
 'Ditlev Jaeger Holm',
 'Jonathan Dolan',
 'Mads Christophersen',
 'Tobias Kuenzi',
 'Magnus Johannesen',
 'Erik Jr Timmerman',
 'Cesar Adonis Brito Gonzalez',
 'David Kim',
 'Louis Ducrot',
 'Driss Bourroum',
 'Thomas Fourcade',
 'Harry Huang',
 'Yanis Gaudin',
 'Philip Illum Klindt']

In [493]:
# unique 
player_names = list(set(player_names_t1+player_names_t2))
print(len(player_names))
type(player_names)

610

list

In [494]:
# names df


team1 = pd.DataFrame({'Team1' : player_names_t1})
team2 = pd.DataFrame({'Team2' : player_names_t2})

team1

                  Team1
0         Jun Hao Leong
1          Teck Zhi Soo
2         Mek Narongrit
3      Mithun Manjunath
4            Chirag Sen
..                  ...
507  Ditlev Jaeger Holm
508   Magnus Johannesen
509          Lino Munoz
510     Julien Carraggi
511     Thomas Fourcade

[512 rows x 1 columns]

In [495]:
# names df

team2 = pd.DataFrame({'Team2' : player_names_t2})

team2

                       Team2
0    Kantawat Leelavechabutr
1     Chico Aura Dwi Wardoyo
2              Yee Han Chong
3        Henrikho Kho Wibowo
4            Hashiru Shimono
..                       ...
492           Driss Bourroum
493          Thomas Fourcade
494              Harry Huang
495             Yanis Gaudin
496      Philip Illum Klindt

[497 rows x 1 columns]